version: '3.7'
services:
  database:
    container_name: database
    image: mongo:4.2
    ports:
      - 27017:27017
  development:
    container_name: development
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/local
    stdin_open: true # docker run -i
    tty: true        # docker run -t
